-- Query for fetching contract ABIs in batch
-- Parameters: {ADDRESS_LIST}, {CONTRACTS_TABLE}
SELECT ADDRESS, NAME, ABI, IMPLEMENTATION_ADDRESS
FROM {CONTRACTS_TABLE}
WHERE (ADDRESS IN ({ADDRESS_LIST}) OR IMPLEMENTATION_ADDRESS IN ({ADDRESS_LIST}))
  AND ABI != '' AND ABI IS NOT NULL