-- Query for fetching contract ABIs in batch
-- Parameters: {ADDRESS_LIST}
SELECT ADDRESS, NAME, ABI, IMPLEMENTATION_ADDRESS
FROM decoded_contracts
WHERE (ADDRESS IN ({ADDRESS_LIST}) OR IMPLEMENTATION_ADDRESS IN ({ADDRESS_LIST}))
  AND ABI != '' AND ABI IS NOT NULL